### ISSUE TITLE
Code links broken in the paper

### ISSUE THREAD

**Issue by Emasoft** [Wang-ML-Lab/llm-continual-learning-survey#1]
In the paper most of the code links are broken. Please publish a revised version.

**Comment by haizhou-shi** [comment]
Hi @Emasoft, 

Thanks for pointing this out! 

We noticed that the first url in Table. 4 is indeed broken with an additional '.'. 
The link to TimeLMs is [https://github.com/cardiffnlp/timelms](https://github.com/cardiffnlp/timelms). 

We have double checked the links in Table. 4 and will submit a new version of the paper. 

Thanks again for the issue and I will close it for now.

**Comment by haizhou-shi** [comment]
Hi @Emasoft, 

As you suggested, here is the link to the revision: https://arxiv.org/abs/2404.16789

**Comment by Emasoft** [comment]
Thank you. The code links now work correctly.
